name: Generate Profile Readme
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */3 * * *'
jobs:
  build:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('yarn.lock') }}
      - run: yarn --frozen-lockfile
      - run: yarn generate:readme
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

